from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any
from domain.models import AssistantResponse, CommandIntent, Interaction, MemoryItem, Skill, PluginMetadata

class PluginInterface(ABC):
    metadata: PluginMetadata
    @abstractmethod
    def skills(self) -> tuple[Skill, ...]: ...
    @abstractmethod
    def can_handle(self, intent: CommandIntent) -> bool: ...
    @abstractmethod
    async def execute(self, intent: CommandIntent) -> AssistantResponse: ...

class AIClient(ABC):
    @abstractmethod
    async def generate(self, prompt: str) -> str: ...
class InteractionRepository(ABC):
    @abstractmethod
    async def initialize(self) -> None: ...
    @abstractmethod
    async def save_interaction(self, user_text: str, assistant_text: str) -> None: ...
    @abstractmethod
    async def get_recent_interactions(self, limit: int = 5) -> list[Interaction]: ...
class MemoryRepository(InteractionRepository):
    @abstractmethod
    async def remember(self, key: str, value: str) -> None: ...
    @abstractmethod
    async def recall(self, key: str) -> MemoryItem | None: ...
    @abstractmethod
    async def list_memories(self) -> list[MemoryItem]: ...
    @abstractmethod
    async def forget(self, key: str) -> bool: ...
class SpeechRecognizer(ABC):
    @abstractmethod
    async def listen_once(self) -> Any: ...
    @abstractmethod
    async def transcribe(self, audio: Any) -> str: ...
class SpeechSynthesizer(ABC):
    @abstractmethod
    async def speak(self, text: str) -> None: ...
class WakeWordService(ABC):
    @abstractmethod
    def is_wake_word_present(self, text: str) -> bool: ...
    @abstractmethod
    def remove_wake_word(self, text: str) -> str: ...
